import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { MeshGradientComponent } from "@/components/mesh-gradient";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.className} antialiased`}>
        {/* 1. MeshGradientComponent with hardcoded values */}
        <MeshGradientComponent
          colors={["#7c3aed", "#8b5cf6", "#a78bfa", "#c4b5fd"]}
          speed={0.6}
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            zIndex: 0,
            width: "100%",
            height: "100%",
          }}
        />

        {/* 2. Main content rendered above the gradient */}
        <div className="max-w-screen-sm mx-auto w-full relative z-[1] flex flex-col min-h-screen">
          <div className="px-5 gap-8 flex flex-col flex-1 py-[12vh]">
            <main className="flex justify-center">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
